In [2]:
import pandas as pd
import numpy as np
url = "https://raw.githubusercontent.com/plotly/datasets/master/supermarket_Sales.csv"
data = pd.read_csv(url)
data = data.rename(columns={
 'Tax 5%': 'Tax',
 'Cost of goods sold': 'Cogs',
 'Gross margin percentage': 'Gross margin pct',
 'Customer stratification rating': 'Rating'
})
data.columns = (
 data.columns
 .str.strip()
 .str.lower()
 .str.replace(' ', '_')
)

In [3]:
#Ejercicio 1
print(data.shape)

(1000, 17)

In [4]:
#Ejercicio 2
print(data.shape)
print(data.columns)
data.head(3)

(1000, 17)
Index(['invoice_id', 'branch', 'city', 'customer_type', 'gender',
       'product_line', 'unit_price', 'quantity', 'tax', 'total', 'date',
       'time', 'payment', 'cogs', 'gross_margin_pct', 'gross_income',
       'rating'],
      dtype='str')

,invoice_id,branch,city,customer_type,gender,product_line,unit_price,quantity,tax,total,date,time,payment,cogs,gross_margin_pct,gross_income,rating
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4

In [5]:
#Ejercicio 3
resultado = data[['city', 'gender', 'total']]
resultado.head()

        city  gender     total
0     Yangon  Female  548.9715
1  Naypyitaw  Female   80.2200
2     Yangon    Male  340.5255
3     Yangon    Male  489.0480
4     Yangon    Male  634.3785

In [6]:
#Ejericcio 4
print(type(data['total']))
print(type(data[['total']]))

<class 'pandas.Series'>
<class 'pandas.DataFrame'>

In [7]:
#Ejericicio 5 
print(data.loc[7, 'product_line'])
print(data.iloc[7, 5])

Home and lifestyle
Home and lifestyle

In [8]:
#ejercicio 6
mascara = data['quantity'] > 8
resultado = data[mascara]
print(resultado.shape[0])

211

In [9]:
#Ejercicio 7
mascara = (data['branch'] == 'A') & (data['total'] > 300)
resultado = data[mascara]
print(resultado.shape)

(141, 17)

In [ ]:
#Ejercicio 8
mascara = data['product_line'].isin(['Food and beverages', 'Fashion accessories'])
print(data[mascara].shape[0])

352

In [ ]:
#Ejercicio 9
mascara = (data['branch'].isin(['A', 'C'])) & (data['total'].between(200, 500))
resultado = data.loc[mascara, ['branch', 'city', 'product_line', 'total']]
resultado.head()

   branch    city            product_line     total
2       A  Yangon      Home and lifestyle  340.5255
3       A  Yangon       Health and beauty  489.0480
6       A  Yangon  Electronic accessories  433.6920
12      A  Yangon  Electronic accessories  246.4875
13      A  Yangon      Food and beverages  453.4950

In [12]:
#Ejercicio 10
data['valor_unitario'] = data['total'] / data['quantity']
print(data['valor_unitario'].head(3).round(2))

0    78.42
1    16.04
2    48.65
Name: valor_unitario, dtype: float64

In [13]:
#Ejercicio 11
data['tipo_compra'] = np.where(data['quantity'] > 6, 'volumen', 'menor')
print(data['tipo_compra'].value_counts())

tipo_compra
menor      602
volumen    398
Name: count, dtype: int64

In [14]:
#Ejercicio 12
resumen = (
    data
    .groupby('branch')['total']
    .mean()
)
print(resumen.round(2))

branch
A    312.35
B    319.87
C    337.10
Name: total, dtype: float64

In [15]:
#ejercicio 13
resumen = (
    data
    .groupby('payment')['total']
    .mean()
)
print(resumen)

payment
Cash           326.181890
Credit card    324.009878
Ewallet        318.820600
Name: total, dtype: float64

In [16]:
#Ejercicio 14
resumen = (
    data
    .groupby('payment')
    .agg(
        facturas=('invoice_id', 'size'),
        unidades=('quantity', 'sum'),
        ingreso=('total', 'sum'),
    )
    .reset_index()
)
print(resumen.round(2))

       payment  facturas  unidades    ingreso
0         Cash       344      1896  112206.57
1  Credit card       311      1722  100767.07
2      Ewallet       345      1892  109993.11

In [17]:
#Ejercicio 15
sucursales = pd.DataFrame({
    'branch': ['A', 'B', 'C'],
    'zona': ['Centro', 'Norte', 'Sur']
})

resultado = data.merge(
    sucursales,
    on='branch',
    how='left'
)

print(resultado.shape)
resultado[['branch', 'city', 'zona', 'total']].head()

(1000, 20)

  branch       city    zona     total
0      A     Yangon  Centro  548.9715
1      C  Naypyitaw     Sur   80.2200
2      A     Yangon  Centro  340.5255
3      A     Yangon  Centro  489.0480
4      A     Yangon  Centro  634.3785